services:
#  discovery-server:
#    build:
#      context: .
#      dockerfile: infra/discovery-server/Dockerfile
#    container_name: discovery-server
#    ports:
#      - "8761:8761"
#    healthcheck:
##      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health || exit 1" ]
#      test: [ "CMD-SHELL", "curl -f http://localhost:8761/actuator/health || exit 1" ]
#      interval: 10s
#      timeout: 5s
#      retries: 10
#      start_period: 30s
#    networks:
#      - ewm-network

#  config-server:
#    build:
#      context: .
#      dockerfile: infra/config-server/Dockerfile
#    container_name: config-server
#    depends_on:
#      discovery-server:
#        condition: service_healthy
#    networks:
#      - ewm-network

#  stats-server:
#    build:
#      context: .
#      dockerfile: stats/stats-server/Dockerfile
#    container_name: stats-server
##    ports:
##      - "9090:9090"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
#      - SPRING_DATASOURCE_USERNAME=user
#      - SPRING_DATASOURCE_PASSWORD=password
##      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
#    depends_on:
#      discovery-server:
#        condition: service_healthy
#      config-server:
#        condition: service_started
#      stats-db:
#        condition: service_healthy
##    healthcheck:
##      test: [ "CMD", "curl", "-f", "http://localhost:9090/actuator/health || exit 1" ]
##      interval: 10s
##      timeout: 5s
##      retries: 10
##      start_period: 30s
#    networks:
#      - ewm-network

  stats-db:
    image: postgres:16.1
    container_name: postgres-ewm-stats-db
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=stats
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d stats" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - ewm-network

#  ewm-service:
#    build:
#      context: .
#      dockerfile: core/main-service/Dockerfile
#    container_name: ewm-service
##    ports:
##      - "8080:8080"
#    environment:
##      - CLIENT_URL=http://stats-server:9090
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-main
#      - SPRING_DATASOURCE_USERNAME=user
#      - SPRING_DATASOURCE_PASSWORD=password
##      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
#    depends_on:
#      discovery-server:
#        condition: service_healthy
#      config-server:
#        condition: service_started
#      ewm-db:
#        condition: service_healthy
#      stats-server:
#        condition: service_started
##    healthcheck:
##      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health || exit 1" ]
##      interval: 30s
##      timeout: 10s
##      retries: 3
##      start_period: 60s
#    networks:
#      - ewm-network

  ewm-db:
    image: postgres:16.1
    container_name: postgres-ewm-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=ewm-main
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d ewm-main" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - ewm-network

networks:
  ewm-network:
    driver: bridge