CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    BIGINT NOT NULL,
    author_id   BIGINT NOT NULL,
    text        TEXT NOT NULL,
    created_on  TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    likes_count INTEGER DEFAULT 0 CHECK (likes_count >= 0)
    );

CREATE TABLE IF NOT EXISTS comment_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id BIGINT NOT NULL REFERENCES comments(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL,
    CONSTRAINT uq_comment_user UNIQUE (comment_id, user_id)
    );