spring:
  application:
    name: aggregator
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: aggregator-group
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: deserializer.UserActionAvroDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: serializer.EventSimilarityAvroSerializer
    topics:
      user-actions: stats.user-actions.v1
      events-similarity: stats.events-similarity.v1

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      enabled: true

aggregator:
  weights:
    view: 0.4
    register: 0.8
    like: 1.0