spring:
  cloud:
    gateway:
      discovery.locator.enabled: false
      routes:
        - id: main-service-public-category
          uri: lb://event-service
          predicates:
            - Path=/categories/**

        - id: main-service-public-comment
          uri: lb://comment-service
          predicates:
            - Path=/events/*/comments

        - id: main-service-public-compilation
          uri: lb://event-service
          predicates:
            - Path=/compilations/**

        - id: main-service-public-event
          uri: lb://event-service
          predicates:
            - Path=/events/**


        - id: main-service-private-events-requests
          uri: lb://event-service
          predicates:
              - Path=/users/*/events/*/requests

        - id: main-service-private-comment
          uri: lb://comment-service
          predicates:
            - Path=/users/*/events/*/comments/**

        - id: main-service-private-event
          uri: lb://event-service
          predicates:
            - Path=/users/*/events/**

        - id: main-service-private-request
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**


        - id: main-service-admin-category
          uri: lb://event-service
          predicates:
            - Path=/admin/categories/**

        - id: main-service-admin-comment
          uri: lb://comment-service
          predicates:
            - Path=/admin/comments/**

        - id: main-service-admin-compilation
          uri: lb://event-service
          predicates:
            - Path=/admin/compilations/**

        - id: main-service-admin-event
          uri: lb://event-service
          predicates:
            - Path=/admin/events/**

        - id: main-service-admin-user
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route: DEBUG
    org.springframework.cloud.gateway.handler: DEBUG