server:
  address: 0.0.0.0
  port: 0

spring:
  application:
    name: main-service
  config:
    import: "configserver:"
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        serviceId: config-server
      retry:
        useRandomPolicy: true
        initial-interval: 2000
        max-interval: 6000

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

